version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: ci/Dockerfile.local
    ports:
      - 6011:6011
    env_file:
      - .docker-env
    depends_on:
      - migrations
      - localstack
  db:
    image: postgres:11.8
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=LocalPassword
      - POSTGRES_DB=notification_api
  migrations:
    build:
      context: ..
      dockerfile: migrations/Dockerfile
    env_file:
      - .docker-env
    depends_on:
      - db
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=iam,sqs
      - DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=0
    healthcheck:
      test: "bash -c 'AWS_ACCESS_KEY_ID=fake AWS_SECRET_ACCESS_KEY=fake aws --endpoint-url=http://localhost:4566 sqs list-queues'"
      interval: 3s
      retries: 5
      timeout: 15s
