version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: ci/Dockerfile.local
    image: notification_api
    ports:
      - 6011:6011
    env_file:
      - .docker-env
    depends_on:
      - migrations
      - localstack
  db:
    image: postgres:11.8
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=LocalPassword
      - POSTGRES_DB=notification_api
  migrations:
    image: notification_api
    env_file:
      - .docker-env
    command: bash -c "make generate-version-file && flask db upgrade"
    depends_on:
      - db
  localstack:
    image: localstack/localstack:0.11.2
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=0
      - HOSTNAME_EXTERNAL=localstack
    healthcheck:
      test: ["CMD", "bash", "-c", "AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar aws --endpoint-url=http://localhost:4566 sqs list-queues"]
      interval: 15s
      retries: 5
      timeout: 3s
  celery:
    image: notification_api
    env_file:
      - .docker-env
    command: ["sh", "-c", "./scripts/run_celery.sh"]
    depends_on:
      - app
      - localstack
