version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: ci/Dockerfile.local
    ports:
      - 6011:6011
    environment:
      - TWILIO_ACCOUNT_SID=
      - TWILIO_AUTH_TOKEN=
      - TWILIO_FROM_NUMBER=0123456789
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:LocalPassword@db:5432/notification_api
      - NOTIFY_ENVIRONMENT=development
      - FLASK_APP=application.py
    depends_on:
      - db
  db:
    image: postgres:11.8
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=LocalPassword
      - POSTGRES_DB=notification_api
  migrations:
    build:
      context: ..
      dockerfile: migrations/Dockerfile
    environment:
      - TWILIO_ACCOUNT_SID=
      - TWILIO_AUTH_TOKEN=
      - TWILIO_FROM_NUMBER=0123456789
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:LocalPassword@db:5432/notification_api
      - NOTIFY_ENVIRONMENT=development
      - FLASK_APP=application.py
    depends_on:
      - db
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=iam,sqs
      - DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=0
