version: "3"
services:
  test:
    build:
      context: ..
      dockerfile: ci/Dockerfile.test
    environment: 
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:LocalPassword@db:5432/test_notification_api
      - NOTIFY_ENVIRONMENT=test
    depends_on:
      - db
  db:
    image: postgres:11.8
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=LocalPassword
      - POSTGRES_DB=test_notification_api
